Repository GAIA-X4PLC-AAD/ontology-management-base, pull requests merged in 2025-03, with the labels that each got.

#138 Final review of ontologies
  .github/workflows/branch-push.yml
  CODEOWNERS
  README.md
  automotive-simulator/automotive-simulator_ontology.ttl
  environment-model/VARIABLES.md
  environment-model/environment-model_instance.json
  environment-model/environment-model_ontology.ttl
  environment-model/environment-model_shacl.ttl
  general/VARIABLES.md
  general/general_ontology.ttl
  general/general_shacl.ttl
  georeference/VARIABLES.md
  georeference/georeference_ontology.ttl
  georeference/georeference_shacl.ttl
  hdmap/VARIABLES.md
  hdmap/hdmap_instance.json
  hdmap/hdmap_ontology.ttl
  hdmap/hdmap_shacl.ttl
  leakage-test/leakage-test_ontology.ttl
  manifest/README.md
  manifest/VARIABLES.md
  manifest/manifest_instance.json
  manifest/manifest_ontology.ttl
  manifest/manifest_shacl.ttl
  marketplace-info/VARIABLES.md
  marketplace-info/marketplace-info_instance.json
  marketplace-info/marketplace-info_ontology.ttl
  marketplace-info/marketplace-info_shacl.ttl
  ositrace/ositrace_ontology.ttl
  scenario/VARIABLES.md
  scenario/scenario_instance.json
  scenario/scenario_ontology.ttl
  scenario/scenario_shacl.ttl
  service/service_ontology.ttl
  simulated-sensor/VARIABLES.md
  simulated-sensor/simulated-sensor_ontology.ttl
  simulated-sensor/simulated-sensor_shacl.ttl
  simulation-model/simulation-model_ontology.ttl
  surface-model/VARIABLES.md
  surface-model/surface-model_instance.json
  surface-model/surface-model_ontology.ttl
  surface-model/surface-model_shacl.ttl
  survey/survey_ontology.ttl
Labels: documentation

#135 Create metadata description for V&V report
  CODEOWNERS
  vv-report/VARIABLES.md
  vv-report/vv-report_instance.json
  vv-report/vv-report_ontology.ttl
  vv-report/vv-report_shacl.ttl
Labels: enhancement

#139 add ubuntu wsl install requirements, format readme
  gx/README.md
Labels: documentation

#140 review: BMW harmonization of labels, comments and wording
  automotive-simulator/VARIABLES.md
  automotive-simulator/automotive-simulator_instance.json
  automotive-simulator/automotive-simulator_ontology.ttl
  automotive-simulator/automotive-simulator_shacl.ttl
  environment-model/environment-model_ontology.ttl
  environment-model/environment-model_shacl.ttl
  general/general_ontology.ttl
  georeference/georeference_ontology.ttl
  hdmap/hdmap_ontology.ttl
  leakage-test/leakage-test_instance.json
  leakage-test/leakage-test_ontology.ttl
  manifest/manifest_ontology.ttl
  manifest/manifest_shacl.ttl
  ositrace/VARIABLES.md
  ositrace/ositrace_ontology.ttl
  ositrace/ositrace_shacl.ttl
  scenario/scenario_ontology.ttl
  service/VARIABLES.md
  service/service_instance.json
  service/service_ontology.ttl
  service/service_shacl.ttl
  simulated-sensor/VARIABLES.md
  simulated-sensor/simulated-sensor_ontology.ttl
  simulated-sensor/simulated-sensor_shacl.ttl
  simulation-model/simulation-model_instance.json
  simulation-model/simulation-model_ontology.ttl
  surface-model/surface-model_ontology.ttl
  survey/survey-result-data-offering_instance.json
  survey/survey-service-offering_instance.json
  survey/survey_ontology.ttl
  vv-report/vv-report_ontology.ttl
Labels: bug, enhancement

#152 Minor improvements
  envited-x/PROPERTIES.md
  envited-x/README.md
  manifest/README.md
  scenario/scenario_shacl.ttl
Labels: bug, documentation
